name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-contribution-grid-snake.svg 

      - name: Mover e Commitar a cobrinha gerada
        run: |
          mv github-contribution-grid-snake.svg .  # Move para a raiz, se necessário
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Atualizando cobrinha 🐍" || echo "Nenhuma alteração para commitar"
          git push || echo "Nenhuma alteração para enviar"
